DROP TABLE IF EXISTS video_game_store.user;
CREATE TABLE video_game_store.user(
  id INT AUTO_INCREMENT PRIMARY KEY,
  password VARCHAR(25),
  first_name VARCHAR(150),
  last_name VARCHAR(150),
  email VARCHAR(250),
  address1 VARCHAR(150),
  address2 VARCHAR(150),
  city VARCHAR(100),
  state VARCHAR(100),
  zip VARCHAR(20),
  country VARCHAR(100),
  credit_card_type VARCHAR(50),
  credit_card_number BIGINT,
  credit_card_cvv INT,
  credit_card_expiry DATE,
  last_login DATETIME
);

DROP TABLE IF EXISTS video_game_store.game;
CREATE TABLE video_game_store.game(
  game_id INT AUTO_INCREMENT PRIMARY KEY,
  game_name VARCHAR(150),
  game_description LONGTEXT,
  console VARCHAR(100),
  num_players INT DEFAULT 0,
  coop VARCHAR(4),
  genre VARCHAR(150),
  release_date DATE,
  developer VARCHAR(150),
  publisher VARCHAR(150),
  front_box_art VARCHAR(150),
  back_box_art VARCHAR(150),
  logo VARCHAR(150),
  developer_logo VARCHAR(150),
  price FLOAT,
  discount FLOAT DEFAULT 0
);

DROP TABLE IF EXISTS video_game_store.comments;
CREATE TABLE video_game_store.comments(
  comment_id int AUTO_INCREMENT PRIMARY KEY,
  user_id INT REFERENCES video_game_store.user(user_id),
  game_id INT REFERENCES video_game_store.game(game_id),
  comment_date DATE,
  comment_details VARCHAR(255),
  ratings INT
);

INSERT INTO video_game_store.game VALUES (1, 'Marvel vs. Capcom 2', 'Marvel vs. Capcom 2: New Age of Heroes is a fighting game, developed and published by Capcom. It is the fourth game in the Marvel vs. Capcom series of fighting games. With the fourth installment of this series, Capcom simplified the player controls to make the gameplay more accessible to the wider audience of casual players. The button configuration was trimmed down to 4 main buttons and 2 assist buttons. The game also features a different air-combo system and 3 on 3 tag, compared to the 2 on 2 tag from previous games in the series.','Sega Dreamcast',2,'No','Fighting','2000-06-30','Capcom','Capcom','Marvel_vs_Capcom_2/front.jpg','Marvel_vs_Capcom_2/back.jpg','Marvel_vs_Capcom_2/logo/logo.jpg','developers/Capcom.jpg',50.90, 3.04);
INSERT INTO video_game_store.game VALUES (2, 'The Legend of Zelda: Breath of the Wild', 'The Legend of Zelda: Breath of the Wild is an action-adventure video game developed and published by Nintendo for the Nintendo Switch and Wii U video game consoles. The game is a part of The Legend of Zelda series, and follows amnesiac protagonist Link, who awakens from a hundred-year slumber to a mysterious voice that guides him to defeat Calamity Ganon before he can destroy the kingdom of Hyrule.

The title\'s gameplay and mechanics constitute a departure from the series\' usual conventions, featuring an open-world environment, a detailed physics engine, high-definition visuals, and voice acting. Announced in 2013, the game was initially planned for release as a Wii U exclusive in 2015, but was delayed twice prior to its release on March 3, 2017. Breath of the Wild was a launch title for the Switch, as well as the final Nintendo-produced game for the Wii U.

Breath of the Wild received universal acclaim from critics, who deemed it to be one of the greatest video games of all time. Critics praised the game\'s open-ended, physics-driven gameplay that encourages player experimentation and exploration, with many calling it a landmark title in open-world game design, although minor criticism was directed at the game\'s technical performance at launch.

Also Available
Special Edition
This bundle includes the game, a Nintendo Switch Sheikah Slate Carrying Case, a Sheikah Eye Collectible Coin, the Relic of Hyrule: Calamity Ganon Tapestry and Weather-Worn Map, and The Legend of Zelda: Breath of the Wild Sound Selection CD.

Master Edition
This bundle includes the game, a Nintendo Switch Sheikah Slate Carrying Case, a Sheikah Eye Collectible Coin, the Relic of Hyrule: Calamity Ganon Tapestry and Weather-Worn Map, a Sound Selection CD, and the Master Sword of Resurrection statue.','Nintendo Switch',1,'No','Action','2017-03-03','Nintendo','Nintendo','The_Legend_of_Zelda_Breath_of_the_Wild/front.jpg','','The_Legend_of_Zelda_Breath_of_the_Wild/logo/logo.jpg','developers/Nintendo.jpg',58.20, 0.22);
INSERT INTO video_game_store.game VALUES (3, 'P.T.', 'P.T. (Playable Teaser) is a first-person psychological survival horror video game directed by Hideo Kojima, developed by Kojima Productions, and published by Konami. Released for the PlayStation 4 on 12 August 2014 as a free download on the PlayStation Network, P.T. served as an interactive teaser for the game Silent Hills, a cancelled installment in the Silent Hill series. In P.T., the player explores a looping corridor of a haunted house while experiencing supernatural events.

P.T. was met with a positive critical reception. It was praised for its horror and the execution of the looping corridor, but was criticized for its complicated puzzles. After the cancellation of Silent Hills, Konami removed P.T. from the PlayStation Store and eliminated the ability to re-download the game. These changes were the subject of controversy.','Sony Playstation 4',1,'No','Horror','2014-08-12','Kojima','Konami','PT/front.jpg','','PT/logo/logo.jpg','developers/Kojima.jpg',87.90, 1.14);
INSERT INTO video_game_store.game VALUES (4, 'Oddworld: New n Tasty', 'Abe\'s back, and the original hero\'s about to face his oddest challenge yet!Chosen by the fickle finger of fate, Abe, first class Floor-Waxer for RuptureFarms, was catapulted into a life of adventure when he overheard plans from his boss, Molluck the Glukkon, to turn Abe and his fellow Mudokons into Tasty Treats as part of a last-ditch effort to rescue Molluck’s failing meatpacking empire.

Can Abe change the fate of thousands and rescue the Mudokons? Can he escape the dark recesses of RuptureFarms and the desolate, uninviting, and downright terrifying surrounding environment?Lead our unlikely hero on his mission because if he doesn’t make it… Abe’s back on the menu!','Sony Playstation 3',1,'No','Platform','2015-04-21','Just','Oddworld','Oddworld_New_n_Tasty/front.jpg','','Oddworld_New_n_Tasty/logo/logo.jpg','developers/Just.jpg',73.70, 4.84);
INSERT INTO video_game_store.game VALUES (5, 'Super Smash Bros: Project M', 'Project M is a community-made mod of Brawl inspired by Super Smash Bros. Melee\'s gameplay designed to add rich, technical gameplay to a balanced cast of characters while additionally enhancing the speed of play. Project M employs new codes which seamlessly add in new, universal features to the entire cast to add technical variety to all characters.','Nintendo Wii',4,'No','Fighting','2014-11-01','Project','Project','Super_Smash_Bros_Project_M/front.jpg','','','developers/Project.jpg',48.60, 0.68);
INSERT INTO video_game_store.game VALUES (6, 'Metal Gear Solid HD Collection', 'From the critically acclaimed director, Hideo Kojima, Metal Gear Solid HD Collection offers a handful of the most popular Metal Gear Solid titles from the past in true HD for the first time ever. Featuring three complete games, Metal Gear Solid 2: Sons of Liberty, Metal Gear Solid: Snake Eater and Metal Gear Solid: Peace Walker, the HD Collection offers old and new fans a chance to experience the epic game play, design and storytelling of the MGS franchise. The "Metal Gear Solid (MGS)" series is the seminal work of Hideo Kojima, Japan\'s master game creator, and the progenitor of the stealth action game genre. The series has become a global phenomenon, with over 27 million copies sold worldwide. The player controls a secret agent from an elite special forces unit who is sent on solo sneaking missions through enemy installations, vast jungles, and sometimes even the thick of battle. Alone and surrounded by the enemy, even a special forces agent will find it tough to come out alive. But that is the secret behind the series\' popularity-the cerebral challenge of figuring out how to avoid combat, and the thrill of sneaking through enemy territory undetected. The MGS series is also known for its storyline, which blends seamlessly with the gameplay. The scenarios are based on extensive research and incorporate the drama of actual developments in society. These elements have made MGS what it is today: a mature work of entertainment that transcends national borders and the confines of video games, and one of the leading products of the Japanese content business.','Sony Playstation 3',1,'No','Stealth','2011-11-08','Kojima','Konami','Metal_Gear_Solid_HD_Collection/front.jpg','Metal_Gear_Solid_HD_Collection/back.jpg','','developers/Kojima.jpg',50.00, 3.21);
INSERT INTO video_game_store.game VALUES (7, '2020 Super Baseball', 'Super Baseball 2020 is a futuristic baseball video game. It was first released in Japan for the Neo Geo in 1991, and then it was later released in North America for the Mega Drive/Genesis (ported by NuFX and released by Electronic Arts) and Super Nintendo Entertainment System (released by Tradewest) in 1993.

The game follows the basic rules of baseball, but there are several upgrades since the game takes place in the year 2020. The most obvious difference from real baseball is that some of the characters in this game are robots. All the human characters are equipped with powerful armor, computer sensors, and jet-packs for improved offense and defensive skills.','Arcade',1,'No','Sports','1991-01-01','Snk','Snk','2020_Super_Baseball/front.jpg','2020_Super_Baseball/back.jpg','','developers/Snk.jpg',48.90, 2.37);
INSERT INTO video_game_store.game VALUES (8, 'Tac Tiles', 'A colorful and challenging puzzle game for smartphones and tablets.
The target is to change a board of multiple colored tiles to a single color with a limited number of moves. A progression of increasingly hard levels await players, and the only tool available is a set of colors for modifying the board. Players must use them intelligently, and create chain reactions to connect as many tiles as possible before running out of moves.','Android',1,'No','Puzzle','2015-12-11','','','Tac_Tiles/front.jpg','','','',22.80, 4.29);
INSERT INTO video_game_store.game VALUES (9, 'StarCraft II: Legacy of the Void', 'You are Hierarch Artanis, leader of the mighty protoss race. Years ago, your homeworld of Aiur fell to the merciless zerg Swarm. Now, at long last, you have raised a powerful fleet of warships known as the Golden Armada, and are poised to reclaim your world. But an ancient evil—Amon—threatens this destiny and the fate of the entire galaxy. Only you can reunite the protoss factions and defeat the coming darkness before it consumes all life in the sector.','PC',4,'No','Strategy','2015-11-10','Blizzard','Blizzard','StarCraft_II_Legacy_of_the_Void/front.jpg','','','developers/Blizzard.jpg',33.90, 3.52);
INSERT INTO video_game_store.game VALUES (10, 'Rolie Polie Olie 2', 'The show focuses on the Polie Family, who live in a teapot-shaped house in a geometric world (Planet Polie) populated by robot-based characters. The stories revolve around a young robot named Olie learning life lessons and going on wacky adventures (either real or imaginative) while growing up. These often include his little sister Zowie, his inventor father, his hard-working mom, his fun-loving grandfather Pappy, and his dog Spot. Although most of the main cast is composed of circular bots, other characters are featured in other shapes, such as Olie\'s friend Billy Bevel and his family, who are square-shaped bots from Planet Cubey.','Microsoft Xbox One',4,'Yes','Action','2016-06-01','Bandai','Bandai','','','','developers/Bandai.jpg',27.10, 2.75);
INSERT INTO video_game_store.game VALUES (11, 'Space Manbow', 'In the year 189 of the stellar calendar, humanity happened upon the ruins of an ancient (and, if the st. 7 decor is anything to go by, rather decadent and malicious) civilization, and sent an archaeological crew to explore them. However, the crew managed to activate the ruins\' defense system.

The system operated by identifying the Sol system as the intruders\' origin, then launched the Sun-Fish ("Manbou" being Japanese for "Sunfish"), an ultimate weapon bio-mechanical starship capable of destroying an entire solar system and protected by an impregnable force-field bubble. The surviving members of the crew, however, find a chance to stop the Sun-Fish. By using an unearthed Manbou-J (i.e. Junior Sun-Fish) fighter and activating a teleportation system in the deepest part of the ruins, one pilot, Cleaver Mule, can actually get inside the force bubble and destroy the Sun-Fish from there.','MSX',1,'No','Shooter','1989-12-21','Konami','Konami','Space_Manbow/front.jpg','Space_Manbow/back.jpg','','developers/Konami.jpg',62.00, 1.57);
INSERT INTO video_game_store.game VALUES (12, 'Tecmo Super Bowl', 'The teams, the players, and the halftime shows are ready for the ultimate football season, and you\'re in control. From the first pre-season game to the playoffs, it\'s your call, your skill, and your team. Can you get to and win the Super Bowl? Tecmo Super Bowl is the only football game to feature onside kicks, blocked passes and kicks, fumbles, pitchout to the running back, player injuries, time-outs, and much, much more! For 1 or 2 players. All 28 NFL teams! Four running plays, four passing plays. Team stats and data. Create your own Pro Bowl. Coach Mode, where you call the plays!','Nintendo Entertainment System (NES)',2,'No','Sports','1991-12-01','Tecmo','Tecmo','Tecmo_Super_Bowl/front.jpg','Tecmo_Super_Bowl/back.jpg','','developers/Tecmo.jpg',69.50, 1.49);
INSERT INTO video_game_store.game VALUES (13, 'Pirates: The Legend of Black Kat', 'More an action-adventure game than a straight naval sim, Pirates: The Legend of Black Kat is designed to offer PS2 and Xbox gamers the chance to live the free but dangerous life of a true pirate. Players will explore five strange new lands that hold unimagined treasures for those brave and skilled enough to claim them. Battle and conquest are also important ingredients in a pirate\'s lifestyle and combat takes place both on land and on the high seas. The player\'s character is quick with a sword and can increase her swashbuckling skills with experience.

Similarly, wealth gained from adventure and victory allows the pirate to upgrade to larger ships with more deadly weaponry. A dozen unique fighting vessels will become available to skilled captains, along with special accoutrements that afford the ships extra powers. Sea battles involve a realistic combination of positioning and timing, as tall ships align themselves to fire on enemy vessels from port- and starboard-mounted weapons and time must be spent reloading the powerful cannons and guns after each shot. The ability to repair damage on the fly is also an important strategic consideration in ship-to-ship fights.

Though the gameplay of this 3D adventure is oriented towards fast action, several elements of role-playing are also incorporated, to move the story along and involve the player more deeply. The lead character Katarina de Leon plots a thoughtful course for her career on the open seas. The "Black Kat" sets sail to uncover mysteries and position herself in circumstances that will increase her overall status among other pirates, securing a position of power. In addition to Katarina\'s well-developed storyline, the game\'s "Captain vs. Captain" battle mode allows a more combat-intensive, freeform style of play.


Pirates ? The Legend of Black Kat, formerly known as Pirates of Skull Cove, is Westwood\'s next-generation pirate game with epic ship battles and thrilling swordplay, starring Black Kat. Take to take to the high seas as Black Kat and master a dozen pirate ships from the simple gunboat to the massive power of a man o\' war. Discover and explore increasingly dangerous and fantastic island worlds and develop Black Kat\'s swordplay skills to master the dagger, cutlass and saber to defeat evil pirate bands and loot their treasures.','Sony Playstation 2',2,'No','Action','2002-02-19','Westwood','Electronic','Pirates_The_Legend_of_Black_Kat/front.jpg','','','developers/Westwood.jpg',70.10, 1.81);
INSERT INTO video_game_store.game VALUES (14, 'Medal of Honor: Underground', 'The game is a prequel to Medal of Honor and it is set in the early stages of WWII. You play as Manon Batiste, who briefed the missions for you in the original Medal of Honor. She is a new member of a small band of French rebels who fight against the tyranny of the Germans.

There are 7 missions in total, featuring 12 different historical weapons. There are NPCs helping you out by cracking safes and driving. Not all enemies are on foot; expect to face tanks and bikes amongst other things. Enemy AI is responsive and sometimes surprising.','Sony Playstation',2,'No','Shooter','2000-11-25','DreamWorks','Electronic','Medal_of_Honor_Underground/front.jpg','Medal_of_Honor_Underground/back.jpg','Medal_of_Honor_Underground/logo/logo.jpg','developers/DreamWorks.jpg',61.50, 1.79);
INSERT INTO video_game_store.game VALUES (15, 'Oddworld: Stranger\'s Wrath HD', 'The premise of Oddworld: Stranger\'s Wrath is that the bounty hunter Stranger must earn moolah (in-game money) by tracking down outlaws with bounties on their heads and apprehending them, bringing them in dead or alive. The game utilizes both third and first-person perspectives. In third person, the player controls Stranger when travelling long distance, platform jumping, rope climbing and melee combat while first person is like that of first person shooter games where ranged weapons are used. Enemies can be approached head on like a straight up action game or stealthily by hiding in long grass out of enemy sight (as indicated via mini map) and luring foes away from or toward the player.[9] Once enemies are encountered, they can be killed or knocked down/stunned temporarily; in this state they can be captured, thus earning more moolah than if they had been captured dead.[10] Upon an attempted capture, Stranger is unable to perform other actions and thus is vulnerable. The player has two status bars, health and stamina. When damage is taken, the health bar drops; if it fully depletes, it will result in the death of Stranger. Stamina drops when the player performs actions like melee attacks or falls from a great height. While it refills itself over time, it can be used to shake off health-bar damage, thus healing the player, but draining the stamina quicker.[9]
One of the game\'s main features is Stranger\'s crossbow that is used in a first person perspective that uses live ammunition in the form of using small fictional versions of real creatures as projectiles for differing effects. Live ammunition can be bought from the game\'s vendors or found scattered throughout the game world. When acquired, two different kinds of ammo can be assigned to the crossbow at any given time for two kinds of firing attack.[3] There are nine critters in total that can be used as ammo, such as Stunkz for stunning large groups of enemies, Thudslugs that work as cannonballs, Boombats that work as rockets, and Bees that are fired at foes like an automatic rifle.[3]
The game incorporates many role-playing elements in the form of earning moolah with each bounty fulfilled allowing it to be spent on upgrades such as crossbow, ammunition, storage and armour upgrades and other items such as binoculars and knuckle dusters.[11]','Sony Playstation 3',0,'No','','2011-12-27','','','Oddworld_Strangers_Wrath_HD/front.jpg','','Oddworld_Strangers_Wrath_HD/logo/logo.jpg','',24.40, 3.36);
INSERT INTO video_game_store.game VALUES (16, 'GameBoy Wars 2', 'Game Boy Wars 2, the second of the Game Boy Wars sequels by Hudson Soft, was released on November 20, 1998. It features support for the Super Game Boy and Game Boy Color. The CPU\'s decision-making algorithm has once again been improved and the game now displays which spaces the player can move into or attack when they\'re moving a unit, allowing for clearer decision making process for the player. There are 54 new maps in Game Boy Wars 2.','Nintendo Game Boy',2,'No','Strategy','1997-11-20','Hudson','Hudson','GameBoy_Wars_2/front.jpg','','','developers/Hudson.jpg',76.20, 0.83);
INSERT INTO video_game_store.game VALUES (17, 'Disney\'s Hercules', 'You are Hercules... the strongest man on Earth. After learning of your true origins, you are informed by the mighty Zeus that no mortal may join the gods unless he has proven himself a hero. So, the adventure begins. Do what you must to pass each of your deadly tests, become a true hero and take your rightful place on Mt. Olympus!','Nintendo Game Boy',1,'No','Action','1997-07-01','Tiertex','THQ','Disneys_Hercules/front.jpg','','','developers/Tiertex.jpg',21.30, 4.48);
INSERT INTO video_game_store.game VALUES (18, 'The Testament of Sherlock Holmes', 'Scrutinized by Scotland Yard, doubted by his stalwart companion Dr. John Watson, and behaving more erratically than ever, Sherlock Holmes is in what might be his darkest hour yet. His recent triumph in the case of a missing set of priceless jewels has turned to disaster; the necklace\'s owner accuses Holmes of returning a forgery to him, and there seems to be no evidence at the ready to clear his name. Has Sherlock Holmes become a criminal? If he is indeed a thief, what else is he capable of? As the questions and suspicions mount, will salvation be found or will there be nothing to stop the famous detective\'s seeming descent into darkness...','Sony Playstation 3',1,'No','Adventure','2012-09-25','Frogwares','Atlus','The_Testament_of_Sherlock_Holmes/front.jpg','','','developers/Frogwares.jpg',40.60, 0.06);
INSERT INTO video_game_store.game VALUES (19, 'Deer Drive', 'Bring all the ammo you can get your hands on, because open season just arrived - big time! Deer Drive is an arcade-style 3D deer hunting game - take aim from cover, and pick off the best trophies. It\'s just pure shooting fun, as herds of deer are driven into your sights!','Nintendo Wii',0,'Yes','','2008-12-16','Kouyousha','Mastiff','Deer_Drive/front.jpg','','','developers/Kouyousha.jpg',39.90, 4.58);
INSERT INTO video_game_store.game VALUES (20, 'Bubsy in: Claws Encounters of the Furred Kind', 'In this 15-level action game the player is Bubsy the bobcat, who has to defeat the Woolies the aliens, which steal balls of yarn. There are five different locations such as jungle, wild west, etc., where the player has to jump and land on their enemies to kill them. Each time to finish the level the player has to defeat the boss, who sits in an alien ship.','Sega Mega Drive',2,'No','Platform','1993-01-01','Accolade','Accolade','Bubsy_in_Claws_Encounters_of_the_Furred_Kind/front.jpg','','Bubsy_in_Claws_Encounters_of_the_Furred_Kind/logo/logo.jpg','developers/Accolade.jpg',29.00, 0.38);
INSERT INTO video_game_store.game VALUES (21, 'Kung Fu High Impact', '"No overview is currently available for this title."','Microsoft Xbox 360',0,'No','Fighting','2011-11-21','Virtual','UTV','Kung_Fu_High_Impact/front.jpg','Kung_Fu_High_Impact/back.jpg','','developers/Virtual.jpg',39.70, 4.22);
INSERT INTO video_game_store.game VALUES (22, 'Buzz Lightyear of Star Command', 'Buzz Lightyear is out to rid the universe of evil. With the aid of his friends at Star Command Mira, Booster, and X-R Buzz will battle Emperor Zurg, Gravatina, Torque, Skreel, and others in 14 levels that span seven different worlds. On each stage, chase the villain causing trouble and try to beat him to the getaway point. Along the way, pick up coins that can be used to purchase new weapons (arc laser, ice gun, proximity grenades, rocket launcher, gatling gun, and others), shields, jetpacks, hover boards, and other items. Cash can also be used to purchase the services of boost pads and teleports that will let Buzz bypass certain portions of the level. Will Buzz be able to put an end to Emperor Zurg\'s attempts to take over the universe? Only by playing BUZZ LIGHTYEAR OF STAR COMMAND will you be able to find the answers to that question.','Sony Playstation',1,'No','Action','2000-10-12','Traveller','Activision','Buzz_Lightyear_of_Star_Command/front.jpg','','','developers/Traveller.jpg',58.70, 0.52);
INSERT INTO video_game_store.game VALUES (23, 'Super Sprint', 'Super Sprint is a racing game for one or two players. Gameplay is from an overhead view of the racetrack. The racetracks start simple and gradually get more complicated, and may also feature obstacles ranging from traffic cones to tornadoes. Occasionally wrenches will appear in the roadway, and when collected they can be used after a race to power up your car with better tires, better acceleration or a higher top speed.','Nintendo Entertainment System (NES)',2,'No','Racing','1989-01-01','Atari','Tengen','Super_Sprint/front.jpg','Super_Sprint/back.jpg','Super_Sprint/logo/logo.jpg','developers/Atari.jpg',37.50, 4.67);
INSERT INTO video_game_store.game VALUES (24, 'Attack of the Mutant Penguins', 'In the distant galaxy of Bleurggh, an evil (but reasonably stupid) band of aliens picked up some of Earth\'s television signals. Unfortunately for them, they could only tune in a wildlife program. They figured the Earth would be a pushover to invade, so they disguised themselves as its inhabitants -- penguins! Word of the invasion has reached those champions of intergalactic do-goodery, Bernard and Rodney. Now, with their help, you must prevent the alien mutant penguins from triggering the Doomscale and destroying the Earth. Are you up to the challenge?','Atari Jaguar',0,'No','','1996-03-01','Sunrise','Atari','Attack_of_the_Mutant_Penguins/front.jpg','Attack_of_the_Mutant_Penguins/back.jpg','Attack_of_the_Mutant_Penguins/logo/logo.jpg','developers/Sunrise.jpg',73.80, 2.74);
INSERT INTO video_game_store.game VALUES (25, 'Street Hoop', 'Street Slam is a 3-on-3 street basketball game. One or two players can choose among 10 teams: France, Spain, U.S.A., Italy, Germany, Taiwan, United Kingdom, China, Japan and South Korea (in the European and Japanese versions. The U.S.A. version features local cities). The teams are rated in 1 to 9 points on four attributes (dunk, 3 point, speed and defense). Each game lasts two halves of 2 minutes each. The game ends if the player loses the first half, needing to spend a continue to play the second half.

When on offense, the player can perform 2 or 3 point shots by pressing the A button. The B button is used to pass the ball. Pressing A and B together throws the ball high in the air, catching it meanwhile (by pressing A) causes the player to perform a dunk. When on defense, the player can jump and block by pressing A and cut off and steal by pressing B. A fantasy element is added to the game: a super shot meter is shown at the bottom of the screen for each team. As points are scored, the meter is filled. When the meter is full, the player can perform a super dunk by pressing A within the 3 points shot line, making the player jump 10 meters in the air.','Neo Geo',2,'No','Sports','1994-01-01','Data','SNK','Street_Hoop/front.jpg','Street_Hoop/back.jpg','Street_Hoop/logo/logo.jpg','developers/Data.jpg',45.40, 4.99);
INSERT INTO video_game_store.game VALUES (26, 'NBA 07', 'NBA 07 is a basketball video game which was released on September 26, 2006. The product features Los Angeles Lakers guard Kobe Bryant on the cover, with his newly chosen jersey number of 24.

It is the second installment of the NBA: Featuring the Life series by Sony Computer Entertainment, and is a launch game for the PlayStation 3 format. It is the only game released at launch other than Marvel: Ultimate Alliance and Ridge Racer 7 that supports the 1080p high definition video output, which was a major advertising point for the PS3.

On all consoles, the game uses graphics from TNT\'s NBA coverage.

AIAS Nominations (10th Annual Interactive Achievement Awards): Best Sports Game of 2006,[1]','Sony Playstation 3',0,'No','Sports','2006-11-14','','','NBA_07/front.jpg','','','',62.70, 3.40);
INSERT INTO video_game_store.game VALUES (27, 'Konami Collector\'s Series: Arcade Advanced', 'Contains emulated ports of Frogger, Time Pilot, Yie Ar Kung-Fu, Gyruss, Scramble, and Rush-N Attack.','Nintendo Game Boy Advance',2,'No','Action','2002-03-21','Konami','Konami','Konami_Collectors_Series_Arcade_Advanced/front.jpg','','','developers/Konami.jpg',57.80, 3.80);
INSERT INTO video_game_store.game VALUES (28, 'Namco x Capcom', 'The year is 20XX. Arisu Reiji and Xiaomu work for a special unit called Shinra, and they are tasked with investigating spirit and otherworldly disturbances. They are initially investigating a strange "sleeping sickness" in the Shibuya area of Japan, when it becomes apparent that something much larger is at stake. Characters, both good and evil, from other times and other worlds begin appearing in Japan.','Sony Playstation 2',1,'No','Role-Playing','2005-05-26','Monolith','Namco','Namco_x_Capcom/front.jpg','','','developers/Monolith.jpg',73.50, 1.41);
INSERT INTO video_game_store.game VALUES (29, '102 Dalmatians: Puppies to the Rescue', 'The game itself follows the films\' storyline loosely. The player can choose the role of one of two dalmatians, Oddball or Domino, who are out in the backyard looking for treasure. It is not long before the player realizes that a toy found buried in a park was made at one of Cruella de Vil\'s toy factories; this alludes to the fact that Cruella\'s toy sales are down, which ultimately leads to the problem in the storyline. Facing financial ruin from lack of sales, Cruella sets an evil plan in motion - to reprogram her toys to capture any pets in sight. Oddball and Domino are the only puppies in their family who have not been captured when they return from the park. Their parents, Dottie and Dipstick, set out to rescue their puppies, commanding Oddball and Domino to stay home and \'be good.\' The puppies do not listen, and are soon out on their biggest adventure yet - to save their brothers and sisters, and their parents who are captured along the way.','Sega Dreamcast',1,'No','Action','2000-11-15','Crystal','Eidos','102_Dalmatians_Puppies_to_the_Rescue/front.jpg','','102_Dalmatians_Puppies_to_the_Rescue/logo/logo.jpg','developers/Crystal.jpg',56.10, 0.93);
INSERT INTO video_game_store.game VALUES (30, 'Asuka 120% - Burning Festival Final', 'As it\'s prequels, this game was only released in Japan. Much of the features were improved from the Limited version for Sega Saturn. In addition, a Windows port of this game titled "Asuka 120% BURNING Festival Return" was released as the very last entry of the franchise with very minor tweaks added.','Sony Playstation',2,'No','Fighting','1999-05-27','Success','Family','Asuka_120__Burning_Festival_Final/front.jpg','Asuka_120__Burning_Festival_Final/back.jpg','','developers/Success.jpg',70.90, 1.76);
INSERT INTO video_game_store.game VALUES (31, 'Wipeout: The Game', 'In Wipeout: The Game, players will prove they have what it takes to make it to the grand finale "Wipeout Zone" for their chance to be proclaimed champion. Four players can compete at the same time, even allowing players to hurl objects at and taunt their opponents. The video game features everything that people love about the hit ABC show, including commentary from the show\'s hosts, John Anderson, John Henson and co-host Jill Wagner. Players will have to run, jump and dodge all of Wipeout\'s various obstacles, including the brutal Sucker Punch, the beloved Big Balls, and the insanely difficult Sweeper.','Nintendo Wii',0,'No','','2010-06-22','A','Activision','Wipeout_The_Game/front.jpg','Wipeout_The_Game/back.jpg','','developers/A.jpg',65.50, 2.93);
INSERT INTO video_game_store.game VALUES (32, 'The Guy Game', 'The Guy Game is an adult video game for the PlayStation 2, Xbox and PC platforms published in 2004 by Gathering of Developers and developed by now-defunct Top Heavy Studios (it was the team\'s only game). Presented in a trivia gameshow style supporting up to four players, it consists of about 1,000 questions spread out over 20 episodes. Much of the game involves watching live-action video footage of young women in bikinis, and as the player succeeds in the game the women eventually expose their breasts. The game garnered much controversy and was the subject of a lawsuit.','Microsoft Xbox',1,'No','Puzzle','2004-08-30','Top','Gathering','The_Guy_Game/front.jpg','','','developers/Top.jpg',75.60, 1.18);
INSERT INTO video_game_store.game VALUES (33, 'GamersGoMakers', 'In GamersGoMakers, you found a little company creating the first video games in history. Create your first game with only basic sound and simple graphics available in the year 1980. You´re one of the pioneers entering the rising global market for computer games.','PC',1,'No','Construction','2014-08-08','gnifrebel','gnifrebel','GamersGoMakers/front.jpg','','','developers/gnifrebel.jpg',68.10, 3.04);
INSERT INTO video_game_store.game VALUES (34, 'Arabian Nights: Sabaku no Seirei-ou', 'In this Japan-exclusive Super Famicom game, the player assumes the role of an orphan named Shukran, who is accompanied by the djinn Ifrit on her adventures to bring peace to her desert homeland.','Super Nintendo (SNES)',1,'No','Role-Playing','1996-06-14','Pandora','Takara','Arabian_Nights_Sabaku_no_Seireiou/front.jpg','','','developers/Pandora.jpg',28.50, 2.28);
INSERT INTO video_game_store.game VALUES (35, 'Great Volleyball', 'Great Volleyball (グレートバレーボール) is a sports game developed and published by Sega for the Sega Master System. It is part of the Great Sports series and was released internationally in 1987.','Sega Master System',2,'No','Sports','1987-01-01','Sega','Sega','Great_Volleyball/front.jpg','Great_Volleyball/back.jpg','Great_Volleyball/logo/logo.jpg','developers/Sega.jpg',49.20, 3.32);
INSERT INTO video_game_store.game VALUES (36, 'Chicken Shoot', 'Chicken Shoot is a gallery shooting game based on free 2003 flash game of the same name. Played from the first-person perspective, the player points the Wii remote and shoots all chickens that fly across the screen. Different kinds of guns can be picked up and every now and then enemies thrown an egg towards the screen that needs to be blown up quickly. Extra points are awarded for shooting certain background items, bombs destroy everything on the screen, food can be picked up to refill energy (Arcade) and clocks add more time (Classic).','Nintendo Wii',0,'No','Shooter','2007-07-05','Calaris','Destination','Chicken_Shoot/front.jpg','Chicken_Shoot/back.jpg','','developers/Calaris.jpg',40.30, 3.05);
INSERT INTO video_game_store.game VALUES (37, 'Advanced V.G.', 'An updated version of the original Variable Geo game for the NEC PC9800 which adds three new playable characters, a storyline which features Yuka as the main character (who has a clone), and includes a pair of "True" bosses, the genetically engineered "Hybrid" warriors K-1 and K-2. This game was originally released for the NEC Turbo-CD later updated for Sega Saturn and Sony PlayStation with updated graphics and sound. The only major difference between the Saturn and PlayStation versions is that the Saturn version retains the "Graphic Mode" setting which allows the viewing of the hentai scenes, not available in the PlayStation version.','Sony Playstation',2,'No','Fighting','1996-03-19','TGL','TGL','Advanced_VG/front.jpg','Advanced_VG/back.jpg','','developers/TGL.jpg',46.00, 3.84);
INSERT INTO video_game_store.game VALUES (38, 'Action Man: Destruction X', 'The master criminal Dr. X is up to his old tricks again! This time he has hatched a geo-strategic plan to steal valuable scientific secrets and take over the world! Only Action Man can stop him!
Seek out Dr. X on a trail through three different cities around the world. Using a variety of vehicles in a combination of race, chase and rescue missions you must catch Dr. X before he triggers his weapons of mass destruction!','Sony Playstation',1,'No','Action','2000-11-01','Blitz','3DO','Action_Man_Destruction_X/front.jpg','Action_Man_Destruction_X/back.jpg','','developers/Blitz.jpg',46.80, 3.38);
INSERT INTO video_game_store.game VALUES (39, 'Spice World', 'Join the Spice Girls as they enter their own interactive dimension.

Interactive magazine with exclusive interviews and behind-the-scenes footage.
Create your own remixes of five of your favorite Spice Girls songs.
Become your favorite Spice Girl and practice individual dance routines.
Choreograph all the Spice Girls for their special live shows - on your TV!','Sony Playstation',1,'No','Music','1998-07-31','SCE','Sony','Spice_World/front.jpg','Spice_World/back.jpg','','developers/SCE.jpg',54.30, 0.73);
INSERT INTO video_game_store.game VALUES (40, 'Guilty Gear Isuka', '"No overview is currently available for this title."','Arcade',0,'No','',NULL,'','','Guilty_Gear_Isuka/front.jpg','','Guilty_Gear_Isuka/logo/logo.jpg','',69.10, 1.11);
INSERT INTO video_game_store.game VALUES (41, 'Adventure Apes and the Mayan Mystery', 'The Mayan Mystery is a retro-inspired metroidvania with an emphasis on exploration. You play as Mitch, and with the help of your best friend (Otis) and mentor (Dr.A), must stop Horatio Hawk from escaping the Mayan temple with a magical artifact!

This is the first in a series of games that will take the Adventures Apes from one location to the next, one era to the next, all in an effort to keep the world\'s most precious treasures out of Horatio\'s hands!

The full version one the Adventure Apes Webpage has 5 bosses and more than 100 rooms plus an illustrated instruction booklet! :)','PC',0,'No','Platform','2012-05-05','ScaryPotato','','Adventure_Apes_and_the_Mayan_Mystery/front.jpg','','','developers/ScaryPotato.jpg',83.30, 1.71);
INSERT INTO video_game_store.game VALUES (42, 'The Hunter 2012', '"No overview is currently available for this title."','PC',0,'No','',NULL,'','','The_Hunter_2012/front.jpg','','','',72.20, 1.58);
INSERT INTO video_game_store.game VALUES (43, 'Donkey Kong Country 2', 'The Donkey Kong Country series returns to the Game Boy Advance in a sequel that features Dixie Kong. She and Diddy Kong must team up to rescue Donkey Kong from the evil Kaptain K. Rool. You\'ll play as both Diddy and Dixie, and master their different attacks. Test your skills and beat the clock in Diddy\'s Dash, or race against your friends to see who\'s the fastest. You can play the game solo or challenge your friends in new bonus games such as Funky\'s Flights and Bag a Bug.','Nintendo Game Boy Advance',0,'No','Platform','2004-11-15','Rare','Nintendo','Donkey_Kong_Country_2/front.jpg','Donkey_Kong_Country_2/back.jpg','','developers/Rare.jpg',21.90, 3.54);
INSERT INTO video_game_store.game VALUES (44, 'DoubleTheSnake', 'DoubleTheSnake (doublesnakegame.com) is a double snake game (two player snake game) in JavaScript for browser (no installation, no plugins, just a good browser).','PC',2,'No','Action','2014-08-01','','doublesnakegame','DoubleTheSnake/front.jpg','','','',20.70, 3.38);
INSERT INTO video_game_store.game VALUES (45, 'Superhero League of Hoboken', 'Superhero League of Hoboken is a hybrid of adventure and role-playing, set in a post-apocalyptic wasteland in the Northeastern United States. Toxic pollution and war have reduced the United States to a state of anarchy, except for the occasional city-state. Almost the entire area is covered by water, and dangerous mutants roam the wasteland. The player takes on the role of the Crimson Tape, the new leader of the Superhero League of Hoboken, imbued with the amazing power to Create Organizational Charts. The initial team also includes Tropical Oil Man (capable of raising the cholesterol level of his opponents), Robomop (an intelligent kitchen appliance capable of cleaning up almost any mess), Iron Tummy (capable of eating spicy foods without any distress), Captain Excitement (whose "aura of lethargy and dullness" can put many opponents to sleep instantly), and Mademoiselle Pepperoni (capable of seeing inside a pizza box without even opening it).

The goal of the game is to complete missions assigned by the Commissioner and relayed via the League\'s computer, Matilda. Gradually, the player will raise Hoboken League\'s ranking, and finally be able to take on the evil Dr. Entropy who is seeking to thwart the rebirth of civilization. As the League\'s ranking and prestige grow, new superheroes with exotic names and superpowers will join up and make life easier.

Gameplay is divided into adventure and role-playing sections. Adventure gameplay manifests itself in the overall structure of the game: to complete a mission, the player must travel to various locations, talk to non-playable characters, and solve predominantly inventory-based puzzles. The interface for the adventure parts of the game is similar to other late Legend Entertainment titles such as Death Gate: locations are presented as still first-person view screens, and the player selects verb commands to interact with the environment. These locations also usually contain shops where the player can buy weapons, equipment and items to outfit the heroes.

The exploration of the game world that contains all the individual locations is done in a role-playing style. The player navigates the party of heroes over top-down overworld screen, gradually exploring larger areas and accessing new locations. During the exploration, enemies attack the party randomly. Combat is viewed from first-person perspective and is turn-based. Heroes have a range of stats (brawn, brains, toughness, and health) and numerous equipment slots along with their superpowers, which can be used in combat beside regular attacks. The party of heroes may include up to nine active combatants. Experience points are collected following battle victories, eventually leveling up the playable characters.

The player also receives experience for fully exploring areas, as well as eliminating all the enemies in a given area (after a series of random encounters enemies eventually stop attacking). Often specific items must be acquired in order to traverse certain terrain types (e.g. deep water) or gain access to subway lines that connected between various areas. Text comments appear not only in adventure parts, but also during combat, humorously describing the course of the battle. The CD version of the game includes voice acting.','PC',0,'No','Adventure','1994-01-01','Legend','Legend','Superhero_League_of_Hoboken/front.jpg','Superhero_League_of_Hoboken/back.jpg','','developers/Legend.jpg',80.10, 4.45);
INSERT INTO video_game_store.game VALUES (46, 'Tony Hawk\'s Pro Skater 2X', 'Tony Hawk\'s Pro Skater 2x was designed to take full advantage of the technical capabilities of Xbox. The game features the franchise\'s signature gameplay, intuitive controls, all of the levels from both Tony Hawk\'s Pro Skater 2 and the original Tony Hawk\'s Pro Skater, in addition to more populated environments, brand new levels, realistic special effects and smoother lifelike animations. The inclusion of system link gameplay brings the skateboarding experience to life.','Microsoft Xbox',2,'No','Action','2001-11-14','Treyarch','Activision','Tony_Hawks_Pro_Skater_2X/front.jpg','Tony_Hawks_Pro_Skater_2X/back.jpg','','developers/Treyarch.jpg',22.00, 3.94);
INSERT INTO video_game_store.game VALUES (47, 'MVP Baseball 2004', 'Step up to the plate for the second iteration of EA Sports\' MVP Baseball. You can sim, manage, or play your way through 120 years of your MLB, AAA and AA franchise. Manage and play as all three teams - develop your farm and win the World Series - even the Tigers have a chance! Two mini-modes let you play head to head with friends or the CPU to test your batting and pitching skills. You can also play in classic fields using classic players like Babe Ruth and Jackie Robinson. Hundreds of uniforms to choose from and thousands of animations to bring the players to life.','Sony Playstation 2',0,'No','Sports','2004-03-09','EA','EA','MVP_Baseball_2004/front.jpg','MVP_Baseball_2004/back.jpg','','developers/EA.jpg',33.30, 2.94);
INSERT INTO video_game_store.game VALUES (48, 'Ken Griffey Jr. Presents Major League Baseball', 'Ken Griffey Jr Presents Major League Baseball is a baseball simulation featuring Ken Griffey Jr. of the "Nintendo Owned" Seattle Mariners. This licensed game allows you to play with all 28 Major League Teams in their own stadiums and over 700 player names (not likenesses). You control your pitcher or batter as well your fielders. The game allows you to play and save a 26, 78 or 162 game season.','Super Nintendo (SNES)',0,'No','Sports','1994-03-01','Software','Nintendo','Ken_Griffey_Jr_Presents_Major_League_Baseball/front.jpg','Ken_Griffey_Jr_Presents_Major_League_Baseball/back.jpg','','developers/Software.jpg',76.90, 0.24);
INSERT INTO video_game_store.game VALUES (49, 'Classic NES Series: The Legend of Zelda', 'The Legend of Zelda invented a genre and captivated a gaming generation. Now you can play the timeless NES adventure on your Game Boy Advance! The evil warlock Ganon has imprisoned Princess Zelda and plunged the peaceful land of Hyrule into darkness and despair. Only a young boy named Link has the courage to answer the call for a hero. Will he find the lost Triforce fragments, slay Ganon, and save Princess Zelda? Only you can decide the fate of Hyrule!','Nintendo Game Boy Advance',1,'No','Action','2004-06-07','Nintendo','Nintendo','Classic_NES_Series_The_Legend_of_Zelda/front.jpg','Classic_NES_Series_The_Legend_of_Zelda/back.jpg','Classic_NES_Series_The_Legend_of_Zelda/logo/logo.jpg','developers/Nintendo.jpg',74.00, 2.15);
INSERT INTO video_game_store.game VALUES (50, 'Yuu Yuu Hakusho: Tokubetsu Hen', 'Yuu Yuu Hakusho: Tokubetsu Hen is an Action game, developed and published by Namco, which was released in Japan in 1994.','Super Nintendo (SNES)',0,'No','Action','1994-12-22','Namco','Namco','Yuu_Yuu_Hakusho_Tokubetsu_Hen/front.jpg','','','developers/Namco.jpg',71.40, 2.70);

